"""Alembic environment (Task 1.4). UNVERIFIED — requires a running PostgreSQL.

Migrations run with a synchronous driver (``psycopg``) derived from the async ``postgres_dsn``
by stripping the ``+asyncpg`` suffix. Startup (design §5.5, Requirement 32.3) applies migrations
explicitly and then asserts applied-revision == head before binding the listener.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from app.config import get_settings

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def _sync_url() -> str:
    dsn = get_settings().postgres_dsn
    return dsn.replace("+asyncpg", "+psycopg")


config.set_main_option("sqlalchemy.url", _sync_url())

target_metadata = None  # migrations are hand-written (design §5.5), not autogenerated


def run_migrations_offline() -> None:
    context.configure(
        url=_sync_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
